server:
  port: 8091
  servlet:
    context-path: /course

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.179.225:3306/share?useSSL=false&amp
    username: share
    password: share_by

mybatis:
#  mapper-locations: classpath:mybatis/UserMapper.xml
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.course.model